apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: klusterlet
  namespace: open-cluster-management
spec:
  channel: stable
  installPlanApproval: Automatic
  name: klusterlet
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: klusterlet.v0.2.0
